import getpass
import colorama
from colorama import Fore
import discord
from discord.ext import commands
import os
import getpass
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))

os.system(f'cls & mode 85,20 & title PHAZIFY AUTOPRESSER')
user = input("Name: ")
print(f'''{Fore.GREEN}
 _    __   __    __   ______   ________  ______  ________  __      __ 
|       \ |  \  |  \ /      \ |        \|      \|        \|  \    /  |
| $$$$$$$\| $$  | $$|  $$$$$$\ \$$$$$$$$ \$$$$$$| $$$$$$$$ \$$\  /  $$
| $$__/ $$| $$__| $$| $$__| $$    /  $$   | $$  | $$__      \$$\/  $$ 
| $$    $$| $$    $$| $$    $$   /  $$    | $$  | $$  \      \$$  $$  
| $$$$$$$ | $$$$$$$$| $$$$$$$$  /  $$     | $$  | $$$$$       \$$$$   
| $$      | $$  | $$| $$  | $$ /  $$___  _| $$_ | $$          | $$    
| $$      | $$  | $$| $$  | $$|  $$    \|   $$ \| $$          | $$    
 \$$       \$$   \$$ \$$   \$$ \$$$$$$$$ \$$$$$$ \$$           \$$    
             ___________LOGGED IN AS: {user}___________                                             
                       P1 X PHAZIFY MADE THIS
                                                                                    
        ''' + Fore.GREEN)

token = input("Enter token: ")
sex = input("Keyword: ")
print("READY TO RAPE BLACKS")
###### CODEZZZZZ#######
@client.event
async def on_message(message):
    channel = message.channel
    print("BITCH GOT RAPED:",message.content)
    if message.content.endswith(sex):

        await message.channel.send('FATHER HAS ARRIVED PHAZIFYW 4ORZIW COME PACK')
        await message.channel.send('GIMME YOUR MOMS THROAT')
        await message.channel.send('🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪')
        await message.channel.send('YOUR GRANDFATHER GOT GASSED IN THE GAS CHAMPER')
        await message.channel.send('FUCK UP UR DAD OWNS LGBTQ 🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈🏳️‍🌈')
        await message.channel.send('YOUR DAD GOT 360 NOSCOPED IN THE WW2 WEAK FUCK')
        await message.channel.send('YOUR MOM DEEPTHROAT SUCKED MY BALLS SHITTER')
        await message.channel.send('YOUR ABUSIVE DAD PUT A LATE ABORTION ON YOU')
        await message.channel.send('PHAZIFY ONTOP')
        await message.channel.send('PHAZIFY ONTOP')
        await message.channel.send('U FUCKED UR MOM ANAL AND SHE FARTED IN YO FACE')
        await message.channel.send('FUCK UP ED SHEERAN LOOKING ASS GINGERBREAD')
        await message.channel.send('YOUR MOMS ASS HAS SO MUCH RADIOACTIVE POISON')
        await message.channel.send('☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️☣️')
        await message.channel.send('BEG YOUR FRIENDS TO ACC HOP YOU AINT LASTING')
        await message.channel.send('MORON ASS NIGGA GO JERK OFF ON HENTAI PORN')
        await message.channel.send('HOLY SHIT YOU CANT TAKE THE PRESSURE')
        await message.channel.send('PACK BACK PHAZIFY FLAMING YOUR ASS')
        await message.channel.send('ILL SNATCH YOUR SOUL AND TORTURE U IN HELL☠️')
        await message.channel.send('IM A DEMON WEAK FUCK YOU CANT BE COMPARED 2 ME')
        await message.channel.send('ILL HEAD SLAP YOU WITH A BUTTERSOCK ')
        await message.channel.send('UR DADS FARTS ARE NUKES WEAK FUCK LOOLOOOL ')
        await message.channel.send('KIM JONG UN IS FINNA SIT ON YO FACE')
        await message.channel.send('GAY ASS NIGGER')
        await message.channel.send('LOL YOU LIKE FUCKING TRANNIES')
        await message.channel.send('WEIRD ASS NIGGA HOP OFF THAT DICK AND COME DIE')
        await message.channel.send('GO JERK OFF TO A TRANNY AND THEN PACK ME SON')
        await message.channel.send('KEEP UP SON U TRIPPED OVER YOUR OWN LEGS??')
        await message.channel.send('UR MY GOON NOW LMFAO')
        await message.channel.send('SELL YOUR TEETHS AT THE TOOTHFAIR BROKE SHIT')
        await message.channel.send('UR MOM BOUGHT U SOME REP JORDANS BROKE NIGGA')
        await message.channel.send('WANT ME TO TAME YOU? SON')
        await message.channel.send('BACK INSIDE THE CAGE YOU GORILLA')
        await message.channel.send('DOG ON THE LEASH ')
        await message.channel.send('YOUR MOM SMASHED YOUR BRAINS OUT')
        await message.channel.send('OLOOLOOOL UR MOMS OILED ASS IS THICK ASF')
        await message.channel.send('4ORZI FLAMING YO SHIT')
        await message.channel.send('SAY CHEESE 📷📷📷📷📷📷📷📷📷📷📷📷')
        await message.channel.send('RUN MY SHIT UP BACKWARDS SEED')
        await message.channel.send('GO PLAY POKEMON TRANNY FUCK')
        await message.channel.send('LOLOLOLOL I HUNTED YOUR MOM DOWN IN BED')
        await message.channel.send('BOB THE BUILDER TRIED FIXING YOUR MOMS ASS')
        await message.channel.send('ILL TEAR APART YOUR MOMS LABIES WEAK FUCK')
        await message.channel.send('YOUR ASS GOT HIGH ON GFUEL????😭😭😭')
        await message.channel.send('UR MOM WAS DOING BACKFLIPS ON THE LAUNDRY')
        await message.channel.send('HOP ON A JOB WEAK FUCK CLEAN THE KFC AREA')
        await message.channel.send('I 3D PRINTED YOUR BIG ASS SOMALIAN FOREHEAD')
        await message.channel.send('YOUR ASS WAS IN A NO MEXICAN MERCY VIDEO')
        await message.channel.send('FOCUS U STILL THERE???? TIRED ALREADY??')
        await message.channel.send('GET YOUR BALLS DROPPED THEN PACK BACK')
        await message.channel.send('UR MY SLAVE FAGGOT')
        await message.channel.send('I PUT BLACKWORK TATTOOD ON YOUR BACK')
        await message.channel.send('WORK ON MY PLANTATION BLACK FUCK')
        await message.channel.send('STOP BEATBOXING WITH YOUR MOMS VOICEBOX')
        await message.channel.send('4ORZI ONTOP')
        await message.channel.send('4ORZI ONTOP')
        await message.channel.send('4ORZI ONTOP')
        await message.channel.send('4ORZI ONTOP')
        await message.channel.send('YOUR MOM IS DIAGNOSED WITH BREAST CANCER')
        await message.channel.send('ILL SPOIL UP YOUR SISTER FAGGOT')
        await message.channel.send('U SUCK')
        await message.channel.send('YOU BUILT LIKE A STRAW')
        await message.channel.send('WEAK TRANNY BITCH EYES OPEN')
        await message.channel.send('YO EYES ARE RED DID YO MOM BUST IN YOUR FACE??')
        await message.channel.send('LAME ASS BOY NEEDS A BREAK?')
        await message.channel.send('CHEETO ASS NIGGA')
        await message.channel.send('EAT YOUR NOODLES YOU DOG EATER')
        await message.channel.send('FUCK UP NOW UR DAD IS IN CHEMOTHERAPY 💀💀')
        await message.channel.send('NIGGA FUCK UP YOU EAT YOUR MOMS MODLY TOENAIL')
        await message.channel.send('FAGGOT FOCUS ILL MAKE YOUR POTATO PC CRASH')
        await message.channel.send('YOU WILL RUN THE OLYMPICS WITH ME FAGGOT')
        await message.channel.send('STAY HYDRATED YOURE GONNA NEED THAT FAGGOT')
        await message.channel.send('SKID ASS NIGGA ILL PUT YOU ASLEEP')
        await message.channel.send('BLACK AFRICAN EBOLA LOOKING ASS YOURE A RAT')
        await message.channel.send('LMAOOOOOO CANT FOCUS AND PRESSURE BACK??')
        await message.channel.send('LOOOOL GET BACK ON NICKELODEON YOU LITTLE KID')
        await message.channel.send('OVERWEIGHT BITCH LMAOO YOU GOT OBESITY')
        await message.channel.send('YOUR MOM IS A PROFESSIONAL PORNSTAR LMAOO')
        await message.channel.send('LOL YOUR BROTHER IS A DISABLED SYNDROME FUCK')
        await message.channel.send('FUCK UP LMAOO YOUR MOM TOOK A BUZZCUT')
        await message.channel.send('LOOOL ILL KILL YOUR WHOLE FAMILY THREE')
        await message.channel.send('YOUR AUNT GAVE A WHOLE TRIO STD NASTY SLUT')
        await message.channel.send('YOUR MOM GOT RAILED SO HARD SHES PARALYSED RN')
        await message.channel.send('FUCK UP TOURETTE KID')
        await message.channel.send('INSIDE THE COFFIN FAGGOT YOU DIED')
        await message.channel.send('STFU YOU GHETTO RETARD')
        await message.channel.send('FUCK UP YOUR COUSIN DIED BECAUSE OF OVERDOSIS')
        await message.channel.send('SON GO SLURP UP YOUR MOM BUTT CHEEKS')
        await message.channel.send('LOOOOLOOOOL GO BACK TO THE DOG SHELTER')
        await message.channel.send('GET BACKSTABBED IN THE BACK W A LIGHTSABER')
        await message.channel.send('YO MOMS ASS IS BLACKER THAN THE COLOUR BLACK')
        await message.channel.send('UR MOM GOT FUCKED WITH HER HEAD IN A HAPPYMEAL')
        await message.channel.send('UR AUNT IS A PROSTITUTE')
        await message.channel.send('FOCUS')
        await message.channel.send('FOCUS')
        await message.channel.send('FOCUS')
        await message.channel.send('YOUR MOTHER WAS KICKED BACK BY A KANGAROO')
        await message.channel.send('YOUR MOM GOT FINGERED ANAL WITH A DILDO')
        await message.channel.send('LOOOLOOOL YO GRAND GRANDFATHER GOT EXECUTED')
        await message.channel.send('YOUR ASS LOOKS LIKE A GRAVITY FALLS MONSTER')
        await message.channel.send('LOOOLOOOL ILL KILL YOU INSIDE THE BODYBAG')
        await message.channel.send('NO ONE WILL VISIT YOUR FUNERAL LOOOOL')
        await message.channel.send('UNLOVED UNWANTED FAGGOT LMFAOOO')
        await message.channel.send('I PREDICTED YOUR DEAD ITS IN 10 MINUTES')
        await message.channel.send('UR MOM USED BLACK MAGIC ON YOU LMFAOO')
        await message.channel.send('CLOWN ASS NIGGA GO TO THE CIRCUS')
        await message.channel.send('USE SOME VASELINE FAGGOT')
        await message.channel.send('MICKEY MOUSE LOOKING ASS UR BIG ASS EARS SON')
        await message.channel.send('JERK OFF ON A MANNEQUIN BITCH')
        await message.channel.send('DESPERATE ASS NIGGA GET A BARBIE')
        await message.channel.send('DISCORD HERO LMAO FOCUS')
        await message.channel.send('HOP BACK IN FORTNITE SON')
        await message.channel.send('YOUR NOT HAS DEMENTIA LOLOLOLOLOLOL')
        await message.channel.send('GET YO SHIT SLIPPED L')
        await message.channel.send('MR KRABS SLIPPED OFF YO DICK LOOOOL')
        await message.channel.send('🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀')
        await message.channel.send('GET YO FAT DIABETES FAT ASS OUTTA HERE')
        await message.channel.send('LOLO')
        await message.channel.send('OLO')
        await message.channel.send('LO')
        await message.channel.send('LOOLOO')
        await message.channel.send('OLOL')
        await message.channel.send('LOLO')
        await message.channel.send('LOLOL')
        await message.channel.send('FALL OFF THE MOUNT EVEREST THEN PACK ME')
        await message.channel.send('YO SIS GOT KIPNAPPED BY SOME PREDATOR')
        await message.channel.send('FUCK UP CONTINUE UPLOADING CHILD PORNGRAPHY')
        await message.channel.send('STFU EL CHAPO LOOKING ASS')
        await message.channel.send('GET YO DICK SUCKED BY PENNY WISE')
        await message.channel.send('WANT ME TO CLIP YOU?')
        await message.channel.send('BETTER START FOCUSING')
        await message.channel.send('WONT TAKE LONG BEFORE YOU BELONG TO ME')
        await message.channel.send('WIN ME AND TAKE THE TROPHY')
        await message.channel.send('YO NASTY ASS UP UR MY JUNIOR')
        await message.channel.send('GAYLORDIAN LOOKING ASS')
        await message.channel.send('YO MOM OWNS CUM EMPIRE FAGGOT LMAOO')
        await message.channel.send('MAN GOT DROWNED WITH SAND IN HIS MOUTH')
        await message.channel.send('U FUCKING CANNIBAL LOOOL EAT YO OWN DICK')
        await message.channel.send('TURN AROUND AND OBEY ME ON YOUR KNEES')
        await message.channel.send('FATHER IS HERE')
        await messsage.channel.send('BEG YOUR ALMIGHTY FATHER FOR FORGIVENESS')
        await message.channel.send('REPENT YOURSELF FAGGOT')
        await message.channel.send('SURRENDER YOU CANT OUTLAST ME LMAO')
        await message.channel.send('WEAK MUTUALS LOLOLOLOLO')
        await message.channel.send('WHATCHU FINNA DO SLAP ME W A TISSUE')
        await message.channel.send('PHAZIFY OWNS YOU LOOL')
        await message.channel.send('I OWN YOU FAGGOT')
        await message.channel.send('TRY XRAY VISION WEAK FUCK')
        await message.channel.send('ASSASSIN WANNA BE LOOOOLLOOOL TROLL')
        await message.channel.send('HOPE YOU CHOKE ON MUSTARD GASS RETARD')
        await message.channel.send('OBEY YOUR MAJESTY')
        await message.channel.send('SUCK UR DADS ORIGAMI DICK NASTY BITCH')
        await messsage.channel.send('UR MOM SHOOTS BEANS WITH HER ASS')
        await message.channel.send('MONKEYGO SWING FROM TREE TO TREE')
        await message.channel.send('WHEN YO MOM FARTS IT SOUNDS LIKE A MK14 LOLOOL')
        await message.channel.send('LOOOLOOOLLOOOLL RATIO + BOZO + L')
        await message.channel.send('DONKEY KONG FUCKED YO MOM LMAOAOOA')
        await message.channel.send('LOUD MIC ME ON YOUR CHROMEBOOK LMAOOOO')
        await message.channel.send('LOOOLOOOL FOCUS UP YOU NERD ASS')
        await message.channel.send('UR AUNT AND UR NOT ARE THOTS LOOOL')
        await message.channel.send('UR SOUL GOT SUCKED OUT BY A VAMPIRE')
        await message.channel.send('LOOOL U BUSTED NUTS ON A UNICORN🦄🦄🦄')
        await message.channel.send('SECRET DOWNSYNDROME MONSTER FROM GRAVITY FALLS')
        await message.channel.send('U THOUGHT U HAD SEX BUT IT WAS IN VRCHAT')
        await message.channel.send('LAME ASS NIGGA SITS 24/7 ON CORD AND CANT LAST')
        await message.channel.send('LISTEN TO XXXTENTACION SAD DEPRESSED FUCK')
        await message.channel.send('TRYNA EGO ME? LAST 100 HOURS FAGGOT')
        await message.channel.send('GET YOUR ⚰️ READY UR GONNA GO 😴')
        await message.channel.send('REST IN PIZZ RETARDED BOZO')
        await message.channel.send('HOP ON FLEX WITH YOUR FAKE GUCCI BELT LOOOL')
        await message.channel.send('THIS BLACK NATURO TALKING SHIT????')
        await message.channel.send('NIGGA HAPPY HE WON NINJA IN A BUILD FIGHT')
        await message.channel.send('YOU LOOK LIKE A DARK SKIN LO KUNG FROM WAKANDA')
        await message.channel.send('U THOUGHT U WAS JESUS WALKING OVER WATER??')
        await message.channel.send('YOU WILL BE CREMATED AFTER ILL KILL YOU')
        await message.channel.send('PROFESSIONAL LASER TAG PLAYER LOOOL')
        await message.channel.send('HOP OFF THE DICK AND LAST WITH ME ALONE')
        await message.channel.send('CORNY ASS NIGGA')
        
client.run(token, bot=False)
